# @see https://github.com/marketplace/actions/auto-labeler
comment: |
  🏷 I have applied any labels matching special text in your issue.

  Please review the labels and make any necessary changes.

  To change this behavior, edit the .github/labeler.yml file and/or the
  workflow defined in .github/workflows/label.yml.

labels:
  'dependencies':
    - 'This is an automated pull request from \[Violinist\]'
