name-template: '$RESOLVED_VERSION'
tag-template: '$RESOLVED_VERSION'
categories:
  - title: '🚨 Major changes'
    label: 'major'
  - title: '🚀 Minor changes'
    label: 'minor'
  - title: '🧰 Patch changes'
    label: 'patch'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
template: |
  ## What's new since $PREVIOUS_TAG

  $CHANGES
