---
services:

  _defaults:
    autoconfigure: true
    autowire: true
    bind:
      $cloudConfigFilepath: '@=service("Acquia\\Cli\\Helpers\\LocalMachineHelper").getCloudConfigFilepath()'
      $acliConfigFilepath: '@=service("Acquia\\Cli\\Helpers\\LocalMachineHelper").getAcliConfigFilepath()'
      Webmozart\KeyValueStore\JsonFileStore $datastoreCloud: '@datastore.cloud'
      Webmozart\KeyValueStore\JsonFileStore $datastoreAcli: '@datastore.acli'
    public: true

  # Todo: something like the following instead of enumerating classes
  # Acquia\Cli\:
    # exclude: ../src/Kernel.php
    # public: false
    # resource: ../src

  Acquia\Cli\Helpers\ClientService: ~

  Acquia\Cli\Helpers\LocalMachineHelper: ~

  Acquia\Cli\Helpers\TelemetryHelper: ~

  Acquia\Cli\Command\AuthCommand:
    parent: Acquia\Cli\Command\CommandBase

  # Todo: something like the following instead of enumerating commands.
  # Acquia\Cli\Command\:
  #   resource: ../src/Command
  #   parent: Acquia\Cli\Command\CommandBase
  #   exclude: ../src/Command/CommandBase.php

  Acquia\Cli\Command\CommandBase:
    abstract: true

  AcquiaCloudApi\Connector\Client: ~

  AcquiaCloudApi\Connector\ConnectorInterface: ~

  Psr\Log\LoggerInterface:
    alias: Symfony\Component\Console\Logger\ConsoleLogger

  Symfony\Component\Console\Application: ~

  Symfony\Component\Console\Input\ArgvInput: ~

  Symfony\Component\Console\Input\InputInterface:
    alias: Symfony\Component\Console\Input\ArgvInput

  Symfony\Component\Console\Logger\ConsoleLogger: ~

  Symfony\Component\Console\Output\ConsoleOutput: ~

  Symfony\Component\Console\Output\OutputInterface:
    alias: Symfony\Component\Console\Output\ConsoleOutput

  datastore.cloud:
    class: Webmozart\KeyValueStore\JsonFileStore
    arguments:
      $path: $cloudConfigFilepath
      $flags: 1

  datastore.acli:
    class: Webmozart\KeyValueStore\JsonFileStore
    arguments:
      $path: $acliConfigFilepath
