---
parameters:
  env(ACLI_REPO_ROOT): "%kernel.project_dir%"
  app.data_dir: "%env(HOME)%/.acquia"
  app.repo_root: "%env(ACLI_REPO_ROOT)%"
  app.ssh_dir: "%env(HOME)%/.ssh"
  app.acli_config_filename: 'acquia-cli.json'
  app.cloud_config_filename: 'cloud_api.conf'
  app.acli_config_filepath: "%app.data_dir%/%app.acli_config_filename%"
  app.cloud_config_filepath: "%app.data_dir%/%app.cloud_config_filename%"

services:
  _defaults:
    autoconfigure: true
    autowire: true
    bind:
      $cloudConfigFilepath: '%app.cloud_config_filepath%'
      $acliConfigFilename: '%app.acli_config_filename%'
      # This should be root directory of the repository where acli is being invoked (not the root of acli itself).
      $repoRoot: "%app.repo_root%"
      $sshDir: "%app.ssh_dir%"
      Webmozart\KeyValueStore\JsonFileStore $datastoreCloud: '@datastore.cloud'
      Webmozart\KeyValueStore\JsonFileStore $datastoreAcli: '@datastore.acli'
    public: true

  # Register nearly all Acquia CLI classes as services.
  Acquia\Cli\:
    exclude: [../src/Kernel.php, ../src/Command/Api/ApiCommandBase.php]
    public: false
    resource: ../src

  # All commands inherit from a common base and use the same DI parameters.
  Acquia\Cli\Command\:
    resource: ../src/Command
    parent: Acquia\Cli\Command\CommandBase
    exclude: [../src/Command/CommandBase.php, ../src/Command/Api/ApiCommandBase.php]
  Acquia\Cli\Command\CommandBase:
    abstract: true

  Acquia\Cli\EventListener\ExceptionListener:
    tags:
      - { name: kernel.event_listener, event: console.error, method: onConsoleError}

  # We have multiple datastores using the same class, just different arguments.
  datastore.cloud:
    class: Webmozart\KeyValueStore\JsonFileStore
    arguments:
      $path: '%app.cloud_config_filepath%'
      $flags: !php/const Webmozart\KeyValueStore\JsonFileStore::NO_SERIALIZE_STRINGS
  datastore.acli:
    class: Webmozart\KeyValueStore\JsonFileStore
    arguments:
      $path: '%app.acli_config_filepath%'

  # AcquiaCloudApi services.
  AcquiaCloudApi\Connector\Client: ~
  AcquiaCloudApi\Connector\ConnectorInterface: ~
  AcquiaLogstream\LogstreamManager: ~

  # Psr services.
  Psr\Log\LoggerInterface:
    alias: Symfony\Component\Console\Logger\ConsoleLogger

  # Symfony services.
  Symfony\Component\Console\Application: ~
  Symfony\Component\Console\Input\ArgvInput: ~
  Symfony\Component\Console\Input\InputInterface:
    alias: Symfony\Component\Console\Input\ArgvInput
  Symfony\Component\Console\Logger\ConsoleLogger: ~
  Symfony\Component\Console\Output\ConsoleOutput: ~
  Symfony\Component\Console\Output\OutputInterface:
    alias: Symfony\Component\Console\Output\ConsoleOutput
  Symfony\Component\EventDispatcher\EventDispatcher: ~

  # Amplitude service.
  Zumba\Amplitude\Amplitude: ~
