imports:
  - { resource: '../prod/services.yml' }

services:
  Symfony\Component\Console\Output\BufferedOutput: ~
  Symfony\Component\Console\Output\OutputInterface:
    alias: Symfony\Component\Console\Output\BufferedOutput
    public: true
  Symfony\Component\Console\Input\ArrayInput: ~
  Symfony\Component\Console\Input\InputInterface:
    alias: Symfony\Component\Console\Input\ArrayInput
    public: true
