name: Auto-label pull requests
on:
  pull_request_target:
    types: [opened, synchronize, reopened, labeled, unlabeled]
permissions:
  pull-requests: write
jobs:
  autolabel:
    uses: acquia/.github/.github/workflows/autolabel.yml@main
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
