name: Transition Jira release to "Released"
on:
  release:
    types: [released]

jobs:
  close-issue:
    name: Close issue
    runs-on: ubuntu-latest
    steps:
      - name: Login to Jira
        uses: acquia/gajira-login@server
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
      - name: Transition issue to "Released"
        uses: acquia/gajira-transition@master
        with:
          # @todo How to find this?
          issue: ${{ steps.create.outputs.issue }}
          transition: "Released"